INSERT INTO TB_CARGOS( descricao ) VALUES ('DESENVOLVEDOR JUNIOR I');
INSERT INTO TB_CARGOS( descricao ) VALUES ('DESENVOLVEDOR JUNIOR II');
INSERT INTO TB_CARGOS( descricao ) VALUES ('DESENVOLVEDOR JUNIOR III');
INSERT INTO TB_CARGOS( descricao ) VALUES ('DESENVOLVEDOR PLENO I');
INSERT INTO TB_CARGOS( descricao ) VALUES ('DESENVOLVEDOR PLENO II');
INSERT INTO TB_CARGOS( descricao ) VALUES ('DESENVOLVEDOR PLENO III');
INSERT INTO TB_CARGOS( descricao ) VALUES ('DESENVOLVEDOR SENIOR I');
INSERT INTO TB_CARGOS( descricao ) VALUES ('DESENVOLVEDOR SENIOR II');
INSERT INTO TB_CARGOS( descricao ) VALUES ('DESENVOLVEDOR SENIOR III');

INSERT INTO TB_UNIDADE_TRABALHO ( descricao, endereco ) VALUES ('UNIDADE I', 'RIO DE JANEIRO');
INSERT INTO TB_UNIDADE_TRABALHO ( descricao, endereco ) VALUES ('UNIDADE II', 'SÃO PAULO');
INSERT INTO TB_UNIDADE_TRABALHO ( descricao, endereco ) VALUES ('UNIDADE III','MINAS GERAIS');
INSERT INTO TB_UNIDADE_TRABALHO ( descricao, endereco ) VALUES ('UNIDADE IV', 'ARACAJU');
INSERT INTO TB_UNIDADE_TRABALHO ( descricao, endereco ) VALUES ('UNIDADE V', 'PORTO ALEGRE');

INSERT INTO TB_FUNCIONARIO (cpf, nome, data_contratacao,salario, cargo_id) VALUES ('676.253.985-87','JEAN', TIMESTAMP WITH TIME ZONE '2022-02-01T10:00:00Z',2.500, 2);
INSERT INTO TB_FUNCIONARIO (cpf, nome, data_contratacao,salario, cargo_id) VALUES ('000.000.000-00','Jean Santos Filho', TIMESTAMP WITH TIME ZONE '2022-02-01T10:00:00Z',5.500, 5);
INSERT INTO TB_FUNCIONARIO (cpf, nome, data_contratacao,salario, cargo_id) VALUES ('444.444.444-44','Camilla Santos', TIMESTAMP WITH TIME ZONE '2022-04-01T10:00:00Z',6.500, 6);
INSERT INTO TB_FUNCIONARIO (cpf, nome, data_contratacao,salario, cargo_id) VALUES ('111.111.111-11','Pedro Gomes', TIMESTAMP WITH TIME ZONE '2020-02-01T10:00:00Z',2.000, 1);
INSERT INTO TB_FUNCIONARIO (cpf, nome, data_contratacao,salario, cargo_id) VALUES ('222.222.222.-22','Lucas Sampaio', TIMESTAMP WITH TIME ZONE '2019-02-01T10:00:00Z',1.500, 1);
INSERT INTO TB_FUNCIONARIO (cpf, nome, data_contratacao,salario, cargo_id) VALUES ('333.333.333-33','Maria do Carmo', TIMESTAMP WITH TIME ZONE '2002-02-01T10:00:00Z',7.500, 6);

INSERT INTO FUNCIONARIOS_UNIDADES ( FK_FUNCIONARIO, FK_UNIDADE ) VALUES (1 , 1);
INSERT INTO FUNCIONARIOS_UNIDADES ( FK_FUNCIONARIO, FK_UNIDADE ) VALUES (2 , 3);
INSERT INTO FUNCIONARIOS_UNIDADES ( FK_FUNCIONARIO, FK_UNIDADE ) VALUES (3 , 4);
INSERT INTO FUNCIONARIOS_UNIDADES ( FK_FUNCIONARIO, FK_UNIDADE ) VALUES (4 , 2);
INSERT INTO FUNCIONARIOS_UNIDADES ( FK_FUNCIONARIO, FK_UNIDADE ) VALUES (5 , 5);
